# Dockerfile

FROM python:3.11.4-slim-bullseye
# FROM python:3.11.4-slim-bookworm
# FROM python:3.11.4-bullseye

RUN apt-get update && apt-get upgrade --yes

RUN useradd --create-home warren
USER warren
WORKDIR /home/warren

ENV VIRTUALENV=/home/warren/.venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"

COPY --chown=warren pyproject.toml constraints.txt ./
RUN python -m pip install --upgrade pip setuptools && \
    python -m pip install --no-cache-dir -c constraints.txt ".[dev]"

COPY --chown=warren src/ src/
COPY --chown=warren test/ test/

RUN python -m pip install . -c constraints.txt && \
    python -m pytest test/unit/ && \
    python -m flake8 src/ && \
    python -m isort src/ --check && \
    python -m black src/ --check --quiet && \
    python -m pylint src/ --disable=C0114,C0116,R1705 && \
    python -m bandit -r src/ --quiet

CMD ["flask", "--app", "page_tracker.app", "run", \
     "--host", "0.0.0.0", "--port", "5000"]
